export const DEVICE_ONLINE_ID_LIST = 'DEVICE_ONLINE_ID_LIST'

export const EMPTY_DEVICE_ONLINE_ID_LIST = 'EMPTY_DEVICE_ONLINE_ID_LIST'

export const DEVICE_ID_ACTIVE = 'DEVICE_ID_ACTIVE'

export const PDF_URL = 'PDF_URL'

export const SET_PDF_SHOW = 'SET_PDF_SHOW'
